### ISSUE TITLE
VBScripts as a security issue

### ISSUE THREAD

**Issue by cosine83** [n8felton/Firefox-ADMX#16]
In recent months, using .js and .vbs script files has become a more popular method of ransomware infection and it's becoming a good idea, in the enterprise, to disable the Windows Scripting Host. Sadly, that prevents this solution from working. Are there any plans to move to PowerShell or provide documentation for someone willing to do that work?

**Comment by n8felton** [comment]
Currently, I have no plans to convert this to PowerShell.

There are a number of Microsoft provided scripts that still use VBS; the Office Software Protection Platform script (ospp.vbs), and the Software License Manager script (slmgr.vbs), just to name a couple. Due to still needing to use these VBS scripts, along with a few other in our environment, we will probably not be locking down WSH anytime soon and chose to protect from infections by other means.

If you (or anyone for that matter) are willing to do the work to convert this to PowerShell, please feel free to fork the project. I'm always happy to provide feedback where needed, I just currently do not have the need, and therefore the time, to convert this.
